### ISSUE TITLE
Single sign-on problem when auto creating user account

### ISSUE THREAD

**Issue by joshAppDev** [digi-serve/ab_service_api_sails#43]
### Short Description

Logging in with Okta to the AB site for the first time. Error: Too many tries to create user account.

### Steps to Reproduce

1. Delete your user account from the AB site.
2. Login to the AB site with Okta.
3. Okta will redirect back to AB.
4. Wait for about 30 seconds for page to load.
5. Sails 500 error page: `Error: Too many tries to create user account`

Look at the SITE_USER table. There will be 4 duplicate entries for your user account. If you try to reload the AB site (the / page), it will work now.

### Expected Behavior

The authentication should work the first try, and only one user account should be auto created.

### What Server are you using?

ldhr.hrupdate.org, global.digiserve.org

### Anything else?

See ./api/lib/authUserOkta.js.
It makes an `appbuilder.model-post` service request for the SITE_USER object with this data:
```js
{
    uuid: AB.uuid(),
    username: "username",
    email: "username@example.com",
    password: "Okta",
    languageCode: "en",
    isActive: 1
}
```

For some reason, this triggers a `ER_DUP_ENTRY` error from the DB. But when you look at the table, the new entry was actually created. _I suspect that the model-post service is inserting the entry 2X. The first time works, and then the second time gets the duplicate error because of the same UUID._

The OktaStrategy will retry this operation 3 more times using a new username and UUID. But it will get the `ER_DUP_ENTRY` error each time.

I tried to recreate this manually using POST /app_builder/model/...[site_user].../. It mostly works. I have not discovered what are the required conditions for the error to occur.

But if I delete my user account and login with Okta, it seems to always get the error.

**Comment by nh758** [comment]
The retries are actually from the AB serviceRequest. We retry requests that timeout 5 times. 
See https://github.com/digi-serve/ab-utils/blob/652f044cfc3ee6130d22677ba4c4182693671151/utils/serviceRequest.js#L15
This was intended to handle cases when a service was temporarily offline, however in other cases, like here, this isn't ideal.

We can add `data.longRequest = true` to the `data` object passed in to the serviceRequest(). This will give 90 seconds to resolve the request before retrying instead of the default 5 seconds. Ideally I think serviceRequest should handle a config parameter where we can override the timeout and retry settings. When we add the longRequest we decided against adding a parameter because of how it would affect the existing codebase, but I think we'll need a better solution here.

**Comment by joshAppDev** [comment]
New results suggest that there may be more to this than just the short timeouts. After adding the `longRequest` option, the service request still ends up creating duplicates and failing. Only now it takes much longer to report back. In the end, I get 504 Gateway Timeout on the front end, and `Error: Too many tries to create user account` does still show up in the server console logs.

**Comment by joshAppDev** [comment]
The problem might be from the model-post(?) service trying to fetch data after it finished inserting a new entry.

These log entries are from the `ab_service_appbuilder` container:
```
authUser::"site user.create() successful. Now loading full value from DB."
authUser::"... timeout waiting for request (log_manager.notification), retrying 1/5"
authUser::"... timeout waiting for request (log_manager.notification), retrying 2/5"
authUser::"... timeout waiting for request (log_manager.notification), retrying 3/5"
authUser::"... timeout waiting for request (log_manager.notification), retrying 4/5"
```

The next few entries in the log are gigantic, filled with way more data than is relevant to creating a new user account. This makes me think it's another case of `populate: true`.

Maybe it's here in line 131 from the .create() method?
https://github.com/digi-serve/appbuilder_platform_service/blob/master/platform/ABModel.js

```js
create(values, trx = null, condDefaults = null, req = null) {
    // ...
    req.log(`${this.object.label || this.object.name}.create() successful. Now loading full value from DB.`);
    // ...
                  // make sure we get a fully updated value for
                  // the return value
                  this.findAll(
                     {
                        where: {
                           glue: "and",
                           rules: [
                              {
                                 key: PK,
                                 rule: "equals",
                                 value: returnVals[PK],
                              },
                           ],
                        },
                        offset: 0,
                        limit: 1,
                        populate: true,
                     },
                     condDefaults,
                     req
                  )
                     .then((rows) => {
                        // this returns an [] so pull 1st value:
                        resolve(rows[0]);
                     })
                     .catch(reject);
               });
}
```

I could update it, but this looks like it affects a lot more than just user account creation.

**Comment by joshAppDev** [comment]
Fixed: https://github.com/digi-serve/ab_service_appbuilder/pull/19
